version: '2'

output: prefixed

includes:
  docker: ./Docker.yml

tasks:

  build:
    cmds:

      - task: docker:clone
        vars:
          url: https://github.com/nicholasdille/cicd-lab

      - task: docker:run
        vars:
          image: alpine
          dir: 01_introduction
          command: cp ../java-hello-world/HelloWorld.java .

      - task: docker:run
        vars:
          image: openjdk:jdk
          dir: 01_introduction
          command: javac HelloWorld.java

      - task: docker:build_dind
        vars:
          dir: 01_introduction
          file: Dockerfile
          context: .
          tag: test:latest

  clean:
    cmds:
      - task: docker:clean
