version: "2"

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
  web:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      ENV_DOCKER_REGISTRY_HOST: "registry"
      ENV_DOCKER_REGISTRY_PORT: 5000
    ports:
      - 80:80
    depends_on:
      - registry